Assignment#2: Bank ATM's Management service
istocoana/RoRinternshipWD-A2 pull request #1
Opened 2023-07-25 14:11 UTC by istocoana

### Summary 
**Bank Account**

- individual bank account which has attributes like name, job, email, and address.
- the initialize method sets the initial values for these attributes when a new account is created (constructor). The initial balance of a new user is set to 0. 
- each new user can deposit money in their account, increasing the balance with unlimited money.
- users can withdraw money from their account while enforcing a maximum daily withdrawal limit of $5000. It provides feedback to the user for three scenarios: 

1. If the withdrawal amount exceeds the maximum daily limit, it displays an error message regarding the limit.
2. If the withdrawal amount is greater than the available account balance, it shows an error message indicating insufficient funds.
3. If the withdrawal is valid and there are sufficient funds, it deducts the specified amount from the account balance and informs the user about the successful transaction and the updated account balance.

**Bank System**

- creates an instance variable representing a list of bank accounts. It is initialized as an empty array when a new BankSystem object is created.
- the create_account method allows the creation of a new bank account within the system. It accepts four parameters name, function, email and address creating a new BankAccount object with the details provided and adding it to the list of accounts (@accounts). When the account is created a message is displayed that the account has been successfully created returning the account.

**Main**
- this is a menu of the program.
- 3 initial users are created to show each case of the program when users withdraw money (user1, user2, user3).  
- user1 is the one whose case is acceptable without any error message, user2 tries to withdraw money but he doesn't have enough, and user3's withdrawal exceeds the $5000 per day limit.
- Next, the program prompts the user to create their bank account by entering their name, job, email, and address. The provided details are then used to create a new account using the create_account method.
- The program enters a loop where the user can interact with their account. The user can choose to deposit money, withdraw money, check their balance, or exit the program.
- If the user chooses to deposit or withdraw money, they are prompted to enter the amount they want to deposit or withdraw. The corresponding methods (deposit_money and withdraw_money) are called on the user's account to handle the transactions.
- If the user chooses to check their balance, the program displays their current account balance.
- If the user chooses to exit, the program displays a goodbye message and terminates the loop, effectively ending the program.

**Unit Tests**
- I created a file for each class, bank_account, and bank_system.

_bank_account_spec.rb:_
- let(:bank_account) defines a bank_account variable that is initialized with a new BankAccount object having default attributes.
- describe '#initialize' contains a single test that checks if the initial balance of a newly created BankAccount object is set to 0.
- describe '#deposit_money' contains a test that checks if the deposit_money method adds money to the account balance correctly.
- describe '#withdraw_money': contains tests for different withdrawal scenarios:
1. A test to ensure that a valid withdrawal reduces the account balance correctly.
2. A test to check if attempting to withdraw an amount exceeding the maximum daily limit results in the appropriate error message.
3. A test to check if attempting to withdraw more than the account balance results in the appropriate error message.

_bank_system_spec.rb:_
- describe '#initialize' contains a single test that checks if a new instance of BankSystem initializes with an empty array for the accounts attribute.
-describe '#create_account' test that checks if the create_account method successfully adds a new account to the accounts list of the BankSystem object. The test creates a new BankSystem object, then calls the create_account method with sample details and verifies that the created account is included in the accounts list.

2023-07-26 07:09 UTC, bogdan-boer commented on lib/bank_account.rb
> +end
You are missing an empty line at the end of file

2023-07-26 07:09 UTC, bogdan-boer commented on lib/bank_account.rb
> +  def deposit_money(money)
What happens if the user inputs an negative amount?

2023-07-26 07:09 UTC, bogdan-boer commented on lib/bank_account.rb
> +  def withdraw_money(money)
Same as above

2023-07-26 07:09 UTC, bogdan-boer commented on lib/bank_account.rb
> +  attr_accessor :name, :job, :email, :address, :balance
`:name, :job, :email, :address` sound more like fields for an User than a bank account, you should create a new model for these attributes

2023-07-26 07:09 UTC, bogdan-boer commented on spec/bank_account_spec.rb
> +
You have an extra line here

2023-07-26 12:52 UTC, VictorMotogna commented on lib/bank_account.rb
> +    if money > 5000
The assignment was to check that in 1 day all withdrawals cannot pass 5000$. If I understand correctly, using your approach, I will be able to extract 4.999$ multiple times in the same day.

2023-07-26 12:52 UTC, VictorMotogna commented on lib/bank_account.rb
> +    if money > 5000
I think it would be a good idea to also add a test for this use case

2023-07-26 15:31 UTC, butiricristian requested changes
Left a couple of remarks, but looks good. Nice job 👍

2023-07-26 15:31 UTC, butiricristian commented on lib/user.rb
> +  def set_pin(pin)
Could this be changed to `def pin=`?

2023-07-26 15:31 UTC, butiricristian commented on lib/user.rb
> +    end
I would suggest checking for errors first and returning from the method when finding one. This way we can avoid if-else clauses:
```suggestion
    unless valid_pin?(pin)
      puts "Invalid PIN. It must be a 4-digit number."
      return false
    end
    
    @pin = pin
    puts "PIN set successfully. [#{pin}]"
    true
```

2023-07-26 15:31 UTC, butiricristian commented on lib/main.rb
> +  user_accounts[user_account1.user.name] = user_account1
The main method seems to be getting pretty long. Could we maybe move the user creation into their separate functions: `def create_user1`, `def create_user2`, etc.?

2023-07-26 15:31 UTC, butiricristian commented on modules/transaction.rb
> +      end
Here we can also do the negative check first and return early from the method:
```suggestion
      if money <= 0
        puts "You can't deposit a negative amount!"
        return
      end
```

2023-07-26 15:31 UTC, butiricristian commented on spec/bank_system_spec.rb
> +      expect(BankAccount).to receive(:new).with(User).and_return(User)
I think you need to replace User with a mocked instance here. User is the class name and BankAccount's initialize should receive a User instance not the User class.

2023-07-26 15:31 UTC, butiricristian commented on spec/create_user_spec.rb
> +  end
```suggestion
context 'when an invalid PIN is provided' do
  let(:invalid_pin) { 'invalid' }

  ...
end
```

2023-07-26 15:31 UTC, butiricristian commented on spec/transaction_spec.rb
> +      test_instance = TransactionTest.new(1000)
It's a good practice to define variables with `let` when writing tests and to do any manipulation in `before` methods. This way we separate definitions and actions from expectations

2023-08-01 05:55 UTC, merged

2023-08-03 10:40 UTC, florinionce commented on lib/main.rb
> +      name = gets.chomp
the logic from each action should be extracted

2023-08-03 10:40 UTC, florinionce commented on spec/bank_system_spec.rb
> +      bank_system.create_account(user_instance)
you could use `subjects`
https://www.betterspecs.org/#subject